### ISSUE TITLE
Class 'App\Nova\NestTool' not found

### ISSUE THREAD

**Issue by efolam** [aiman1717a/nest-tool#1]
I added `use Aiman\ThaanaTextField\ThaanaTextField;` in my `Nova/Page.php` resource

but when i use there:
```
NestTool::make()
  ->...;
```

it returns Error:
```
Class 'App\Nova\NestTool' not found
```

**Comment by aiman1717a** [comment]
`use Aiman\NestTool\NestTool;`
Appologize, i had the wrong import in the documentation. use the import above
